"""Summary field indices in .jma file (0-based from start of summary block)."""

SUMMARY_FIELD = {
    "floor_multi_tot": 6,
    "coil_mark_up_percent": 6,
    "coil_misc": 7,
    "comp_0": 8,
    "comp_1": 9,
    "comp_2": 10,
    "comp_3": 11,
    "comp_markup_percent": 14,
    "components_price": 15,
    "cones_vol": 18,
    "cone_total": 19,
    "diam": 20,
    "expan_diam": 21,
    "expan_height": 22,
    "expan_vol": 23,
    "gst": 25,
    "lab_cones_amt": 30,
    "lab_misc_hrs": 32,
    "lab_misc_rate": 33,
    "lab_strakes_amt": 38,
    "lab_components_hrs": 86,
    "lab_components_amt": 87,
    "num_tanks": 56,
    "other_vol": 57,
    "price_quoted": 59,
    "res_barrel_height": 61,
    "single_add_on_0": 65,
    "single_add_on_1": 66,
    "single_add_on_2": 67,
    "multi_add_on_0": 42,
    "multi_add_on_1": 43,
    "multi_add_on_2": 44,
    "steel_sub_tot": 76,
    "steel_mark_up_amount": 75,
    "steel_total": 78,
    "strakes_vol": 77,
    "strake_total": 79,
    "total_vol": 81,
    "tot_cone_height": 82,
    "tot_strake_height": 83,
}

SUMMARY_BLOCK_FIELDS = 89  # fields before MAXNUMCOMPS line
