"""Plain-text email templates for Tank Costing notifications."""

from __future__ import annotations


def user_invite(*, display_name: str, email: str, password: str, login_url: str) -> tuple[str, str]:
    subject = "Your Tank Costing account"
    body = f"""Hello {display_name or email},

An administrator has created a Tank Costing account for you.

Sign in at: {login_url}
Email: {email}
Temporary password: {password}

Please sign in and change your password under Account → Change password.
If MFA is required for your role, set it up under Account → Two-factor authentication.

— Tank Costing
"""
    return subject, body


def password_reset(
    *, display_name: str, email: str, new_password: str, login_url: str
) -> tuple[str, str]:
    subject = "Tank Costing password reset"
    body = f"""Hello {display_name or email},

Your Tank Costing password has been reset by an administrator.

Sign in at: {login_url}
Email: {email}
New password: {new_password}

Please change this password after signing in.

— Tank Costing
"""
    return subject, body


def smtp_test(*, recipient: str) -> tuple[str, str]:
    subject = "Tank Costing — SMTP test"
    body = f"""This is a test message from Tank Costing.

If you received this email, SMTP settings are working correctly.

Recipient: {recipient}

— Tank Costing
"""
    return subject, body


def quote_email(*, customer_name: str, title: str, quote_ref: str | None) -> tuple[str, str]:
    ref = f" ({quote_ref})" if quote_ref else ""
    subject = f"Tank quote{ref}: {title}"
    body = f"""Hello{(' ' + customer_name) if customer_name else ''},

Please find attached the tank costing quote for:

  {title}{ref}

This document was generated by Tank Costing.

— JMA Group
"""
    return subject, body
