"""Generate PDF quote documents from costing data."""

from __future__ import annotations

import io
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.calc.costing import calculate_costing
from app.services.jma_service import payload_to_models


def _money(n: float | None) -> str:
    if n is None:
        return "—"
    return f"${n:,.2f}"


def generate_quote_pdf(
    *,
    title: str,
    quote_ref: str | None,
    payload: dict[str, Any],
    customer: dict[str, Any] | None = None,
) -> bytes:
    cones, strakes, summary, rate = payload_to_models(payload)
    result = calculate_costing(cones, strakes, summary, cones_rate_per_hour=rate)
    t = result.totals

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=20 * mm, rightMargin=20 * mm)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("Tank Costing Quote", styles["Title"]))
    story.append(Spacer(1, 6 * mm))

    meta = [
        ["Job title", title],
        ["Quote / job ref", quote_ref or "—"],
        ["Tank diameter", f"{summary.diam:,.0f} mm"],
        ["Number of tanks", str(summary.num_tanks)],
    ]
    if customer:
        meta.extend(
            [
                ["Customer", customer.get("company_name") or "—"],
                ["Contact", customer.get("contact_name") or "—"],
                ["Email", customer.get("email") or "—"],
            ]
        )
    meta_table = Table(meta, colWidths=[45 * mm, 120 * mm])
    meta_table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    story.append(meta_table)
    story.append(Spacer(1, 8 * mm))

    story.append(Paragraph("Volumes", styles["Heading2"]))
    vol_data = [
        ["Total volume", f"{t.total_vol:,.1f} L"],
        ["Strakes volume", f"{t.strakes_vol:,.1f} L"],
        ["Cones volume", f"{t.cones_vol:,.1f} L"],
        ["Tank liquid height", f"{t.tank_height:,.0f} mm"],
    ]
    vol_table = Table(vol_data, colWidths=[70 * mm, 95 * mm])
    vol_table.setStyle(TableStyle([("BOTTOMPADDING", (0, 0), (-1, -1), 3)]))
    story.append(vol_table)
    story.append(Spacer(1, 6 * mm))

    story.append(Paragraph("Pricing (single tank)", styles["Heading2"]))
    price_data = [
        ["Cones steel", _money(t.cone_total)],
        ["Strakes steel", _money(t.strake_total)],
        ["Steel subtotal", _money(t.steel_sub_tot)],
        ["Steel markup", _money(t.steel_mark_up_amount)],
        ["Steel total", _money(t.steel_total)],
        ["Components (inc markup)", _money(t.comp_tot_inc_markup)],
        ["Labour total", _money(t.labour_tot)],
        ["Single tank (ex GST)", _money(t.single_tank_less_gst)],
        ["Single tank (inc GST)", _money(t.single_tank_inc_gst)],
    ]
    price_table = Table(price_data, colWidths=[70 * mm, 95 * mm])
    price_table.setStyle(
        TableStyle(
            [
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("LINEABOVE", (0, -1), (-1, -1), 1, colors.black),
                ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
            ]
        )
    )
    story.append(price_table)

    components = payload.get("selected_components") or []
    if components:
        story.append(Spacer(1, 8 * mm))
        story.append(Paragraph("Components", styles["Heading2"]))
        comp_rows = [["Type", "Description", "Cost"]]
        for c in components:
            comp_rows.append(
                [c.get("type") or "", c.get("description") or "", _money(float(c.get("cost") or 0))]
            )
        comp_table = Table(comp_rows, colWidths=[35 * mm, 90 * mm, 40 * mm])
        comp_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ]
            )
        )
        story.append(comp_table)

    story.append(Spacer(1, 12 * mm))
    story.append(Paragraph("Generated by Tank Costing — JMA Group", styles["Normal"]))

    doc.build(story)
    return buf.getvalue()
